config:
  storeId: 
    # - 2916

  influence_sheet: ''
  influence_min: 0
  influence_max: 0

  # Perdict period: [PREDICT_START_DATE, PREDICT_START_DATE+PREDICT_LENGTH)
  # predict_start_date can not set to be later than today.
  predict_start_date: '2019-06-23'
  predict_length: 35
  lag_length: 50

  lag_cols: 
    - Sales

  sliding_window_length: 50
  sliding_cols:
    - Sales

  model_list:
    - LGBMRegressor
  
  peak_period:
    - '2017-12-08' 
    - '2018-02-08'
    - '2018-12-10'
    - '2019-02-10'
    # - '2016-12-08'
    # - '2017-01-01'
    # - '2017-12-08'
    # - '2018-01-01'
    # - '2018-12-08'
    # - '2019-01-01'
  
  

